import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { staffJson } from "@/lib/api";
import { FileText, Download } from "lucide-react";

type PayslipRow = {
  id: string;
  employeeId: string;
  period: string;
  totalEarnings: number;
  totalDeductions: number;
  netPay: number;
  generatedAt: string;
};

function formatPeriod(ym: string): string {
  if (!ym || ym.length < 7) return ym;
  const [y, m] = ym.split("-");
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  const monthName = months[parseInt(m, 10) - 1] || m;
  return `${monthName} ${y}`;
}

function formatMoney(n: number): string {
  return new Intl.NumberFormat("en-IN", { maximumFractionDigits: 0 }).format(n);
}

export default function StaffMyPayslips() {
  const [list, setList] = useState<PayslipRow[]>([]);
  const [loading, setLoading] = useState(true);

  function load() {
    setLoading(true);
    staffJson<PayslipRow[]>("/staff/payslips")
      .then(setList)
      .catch(() => setList([]))
      .finally(() => setLoading(false));
  }

  useEffect(() => load(), []);

  async function viewPdf(id: string) {
    try {
      const res = await fetch(`/api/staff/payslips/${id}/file`, { credentials: "include" });
      if (!res.ok) throw new Error("Failed to load PDF");
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      window.open(url, "_blank", "noopener");
      setTimeout(() => URL.revokeObjectURL(url), 60000);
    } catch {
      // ignore
    }
  }

  async function downloadPdf(id: string, period: string) {
    try {
      const res = await fetch(`/api/staff/payslips/${id}/file`, { credentials: "include" });
      if (!res.ok) throw new Error("Failed to load PDF");
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `payslip-${period}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch {
      // ignore
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <FileText className="h-7 w-7 text-emerald-600" />
          My Payslips
        </h1>
        <p className="text-slate-600 mt-0.5">View and download your salary slips.</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Payslips</CardTitle>
          <CardDescription>Click View to open the PDF or Download to save it.</CardDescription>
        </CardHeader>
        <CardContent>
          {loading ? (
            <p className="text-slate-500 py-4">Loading…</p>
          ) : list.length === 0 ? (
            <p className="text-slate-500 py-4">No payslips yet. Payslips are generated by HR for each pay period.</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm border-collapse">
                <thead>
                  <tr className="border-b bg-slate-50">
                    <th className="text-left py-2.5 px-3 font-medium text-slate-700">Period</th>
                    <th className="text-right py-2.5 px-3 font-medium text-slate-700 tabular-nums">Earnings</th>
                    <th className="text-right py-2.5 px-3 font-medium text-slate-700 tabular-nums">Deductions</th>
                    <th className="text-right py-2.5 px-3 font-medium text-slate-700 tabular-nums">Net Pay</th>
                    <th className="text-left py-2.5 px-3 font-medium text-slate-700 w-[140px]">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {list.map((row) => (
                    <tr key={row.id} className="border-b hover:bg-slate-50/50">
                      <td className="py-2.5 px-3 font-medium">{formatPeriod(row.period)}</td>
                      <td className="py-2.5 px-3 text-right tabular-nums">₹ {formatMoney(row.totalEarnings)}</td>
                      <td className="py-2.5 px-3 text-right tabular-nums">₹ {formatMoney(row.totalDeductions)}</td>
                      <td className="py-2.5 px-3 text-right tabular-nums font-medium">₹ {formatMoney(row.netPay)}</td>
                      <td className="py-2.5 px-3">
                        <div className="flex items-center gap-2">
                          <Button variant="outline" size="sm" onClick={() => viewPdf(row.id)}>
                            View
                          </Button>
                          <Button variant="outline" size="sm" onClick={() => downloadPdf(row.id, row.period)}>
                            <Download className="h-4 w-4 mr-1" />
                            Download
                          </Button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
